spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/payment?serverTimezone=Asia/Seoul
    username: pjm
    password: jmjm1102
  kafka:
    cluster:
      bootstrap:
        servers: localhost:9092
    topic: payment-events
    template:
      default-topic: payment-events
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      #      properties:
      #        acks: all
      #        retries: 10
      #        retry.backoff.ms: 1000
    admin:
      properties:
        bootstrap.servers: localhost:9092,localhost:9093,localhost:9094
    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          # show_sql: true
          format_sql: true
logging.level:
  org.hibernate.SQL: debug




eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

