spring:
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
  config:
    activate:
      on-profile: secret

  datasource:
    url: jdbc:mysql://wooyano-db:3306/payment
    username: root
    password: qwe@1234!

  kafka:
    cluster:
      bootstrap:
        servers: kafka1:9092
    topic: payment-events
    template:
      default-topic: payment-events
    producer:
      bootstrap-servers: kafka1:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  admin:
    properties:
      bootstrap.servers: kafka1:9092,kafka2:9093,kafka3:9094
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
    driver-class-name: com.mysql.cj.jdbc.Driver
logging.level:
  org.hibernate.SQL: debug

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL}

  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /api/v1/**